### ISSUE TITLE
Use fastmap and nested node "map" 

### ISSUE THREAD

**Issue by DnD-Crow** [php-etl/rabbitmq-flow#2]
Hello,

We can't use nested nodes with fastmap configuration. This below example can't be executed: 

```
- fastmap:
        expression_language:
          - 'Kiboko\Component\ExpressionLanguage\Akeneo\AkeneoFilterProvider'
        map:
          - field: '[translations][en_US]'
            expression: 'input'
            map:
              - field: '[name]'
                expression: 'input["identifier"] ~" | "~ attribute(input["values"]["variation_name"], locale("en_US"), scope(null, "ecommerce"))'
              - field: '[slug]'
                expression: 'input["identifier"]'
              - field: '[description]'
                expression: 'attribute(input["values"]["description"], locale("en_US"), scope("ecommerce"))'
```

The error : 
>   Invalid configuration for path "etl.satellite.pipeline.steps.1.fastmap.map.1": Your configuration should either con
  tain the "expression" or the "map" field, not both.

It's related to this node part of the configuration: 
```
 map:
          - field: '[translations][en_US]'
            expression: 'input'
            map:
```

I don't find any hints on the code source or in documentation to solve this.

Thank you !

Didier
