### ISSUE TITLE
Collision between current repo and configuration

### ISSUE THREAD

**Issue by DnD-Crow** [php-etl/rabbitmq-flow#3]
Hello,

I'm in a trouble using this plugin on satellite because of some collisions. In the documentation, it's mentioned: 

"This plugin is already integrated into the Satellite package, so you can’t require it with the composer."

But I don't find any dependency to this plugin in satellite main repository.
I solve it by require it manually: `composer require php-etl/rabbitmq-flow`

But I guess there is some delay between the current version and the configuration.
In `Kiboko\Component\Flow\RabbitMQ\Rejection`
Construct: 
```
    public function __construct(
        private Client $connection,
        private string $stepUuid,
        private string $topic,
        private ?string $exchange = null,
    ) {
        $this->channel = $this->connection->channel();
        $this->channel->queueDeclare(
            queue: $this->topic,
            passive: false,
            durable: true,
            exclusive: false,
            autoDelete: true,
        );
    }
```

When the configuration is like this:
```
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        user: 'guest'
        password: 'guest'
        vhost: /
        topic: product.api_rejects
```

Configuration seems to be based on the old version of the construct: https://github.com/php-etl/rabbitmq-flow/commit/38ce28efd3daf12604fc2bd1b1b01abb404ac257

Could you tell me the good way to define MQ with Satellite ? 

Thank you,

Didier
